---
sidebar: sidebar 
permalink: migration/migrate-get-start-ontap.html 
keywords: migration, getting, started, ontap datastores, netapp 
summary:  
---
= Erfahren Sie mehr über die Migration von VMs zu ONTAP -Datenspeichern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Migration von VMware-Workloads zu ONTAP verbessert die Datenverwaltung und Leistung mit Funktionen wie Deduplizierung, Komprimierung und Snapshots.

Diese Migration ermöglicht eine nahtlose Integration, verbesserten Datenschutz und größere Flexibilität bei der Verwaltung virtualisierter Umgebungen und gewährleistet einen reibungslosen Übergang mit minimalen Ausfallzeiten.



== Anwendungsfälle

Wenn Sie eine Migration auf ONTAP gestützte Datenspeicher in Erwägung ziehen, stehen Ihnen hinsichtlich Quelle und Ziel zahlreiche Migrationsoptionen zur Verfügung.

* Migration von Speichersystemen von Drittanbietern (einschließlich vSAN) zu ONTAP -Datenspeichern.
* Migration von VMs im selben vSphere-Cluster
* Migration von VMs über mehrere vSphere-Cluster
* Migration von VMs über vCenter-Server in derselben SSO-Domäne
* Migration von VMs über vCenter-Server in verschiedenen SSO-Domänen
* Migration von VMs zwischen Rechenzentrumsstandorten
* Migration von Speichersystemen von Drittanbietern (einschließlich vSAN) zu ONTAP -Datenspeichern.
* Migration von VMs in einer Hybrid-Cloud-Umgebung


Weitere Informationen zur Migration von VMware-Workloads zu ONTAP gestützten Datenspeichern finden Sie imlink:migrate-vms-to-ontap-datastore.html["Migrieren Sie VMs zu ONTAP -Datenspeichern"] .
