---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: 'Bereitstellung von ONTAP -Speicher für Proxmox Virtual Environment (VE) unter Verwendung von NAS-Protokollen (NFS, SMB) und SAN-Protokollen (FC, iSCSI, NVMe). Wählen Sie das geeignete protokollspezifische Verfahren, um den gemeinsam genutzten Speicher für Ihren Proxmox VE-Cluster zu konfigurieren.' 
---
= Erfahren Sie mehr über Speicherprotokolle für Proxmox VE mit NetApp ONTAP.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bereitstellung von ONTAP -Speicher für Proxmox Virtual Environment (VE) unter Verwendung von NAS-Protokollen (NFS, SMB) und SAN-Protokollen (FC, iSCSI, NVMe). Wählen Sie das geeignete protokollspezifische Verfahren, um den gemeinsam genutzten Speicher für Ihren Proxmox VE-Cluster zu konfigurieren.

Stellen Sie sicher, dass die Proxmox VE-Hosts über FC-, Ethernet- oder andere unterstützte Schnittstellen verfügen, die mit Switches verbunden sind, welche die Kommunikation mit den logischen ONTAP Schnittstellen ermöglichen. Überprüfen Sie immer die https://mysupport.netapp.com/matrix/#welcome["Interoperabilitätsmatrix-Tool"] für unterstützte Konfigurationen. Die Beispielszenarien basieren auf der Annahme, dass auf jedem Proxmox VE-Host zwei Hochgeschwindigkeits-Netzwerkschnittstellenkarten verfügbar sind, die miteinander verbunden werden, um gebündelte Schnittstellen für Fehlertoleranz und Leistung zu schaffen. Für den gesamten Netzwerkverkehr, einschließlich Host-Management, VM-/Container-Verkehr und Speicherzugriff, werden dieselben Uplink-Verbindungen verwendet. Wenn mehr Netzwerkschnittstellen verfügbar sind, sollten Sie erwägen, den Speicherdatenverkehr von anderen Datenverkehrsarten zu trennen.

Informationen zur ONTAP -Speicherarchitektur und den unterstützten Speichertypen finden Sie unter link:proxmox-ontap-architecture.html["Erfahren Sie mehr über die ONTAP -Speicherarchitektur für Proxmox VE."] Und link:proxmox-storage-types.html["Erfahren Sie mehr über die von Proxmox VE unterstützten Speichertypen."]Die


NOTE: Bei Verwendung von LVM mit SAN-Protokollen (FC, iSCSI, NVMe-oF) kann die Volume-Gruppe mehrere LUNs oder NVMe-Namespaces enthalten. In diesem Fall müssen alle LUNs oder Namensräume Teil derselben Konsistenzgruppe sein, um die Datenintegrität zu gewährleisten. Wir unterstützen keine Volume-Gruppen, die sich über mehrere ONTAP SVMs erstrecken. Jede Volume-Gruppe muss aus LUNs oder Namespaces desselben SVM erstellt werden.



== Wählen Sie ein Speicherprotokoll.

Wählen Sie das Protokoll aus, das Ihrer Umgebung und Ihren Anforderungen entspricht:

* link:proxmox-ontap-smb.html["SMB/CIFS-Speicher konfigurieren"] - Konfigurieren Sie SMB/CIFS-Dateifreigaben für Proxmox VE mit Mehrkanalunterstützung für Fehlertoleranz und verbesserte Leistung über mehrere Netzwerkverbindungen.
* link:proxmox-ontap-nfs.html["NFS-Speicher konfigurieren"] - Konfigurieren Sie NFS-Speicher für Proxmox VE mit nConnect oder Session Trunking für Fehlertoleranz und Leistungsverbesserungen durch die Verwendung mehrerer Netzwerkverbindungen.
* link:proxmox-ontap-fc.html["Konfigurieren Sie LVM mit FC"] - Konfigurieren Sie Logical Volume Manager (LVM) mit Fibre Channel für einen leistungsstarken Block-Speicherzugriff mit geringer Latenz über Proxmox VE-Hosts hinweg.
* link:proxmox-ontap-iscsi.html["LVM mit iSCSI konfigurieren"] - Konfigurieren Sie Logical Volume Manager (LVM) mit iSCSI für den Blockspeicherzugriff über Standard-Ethernet-Netzwerke mit Multipath-Unterstützung.
* link:proxmox-ontap-nvme-fc.html["Konfigurieren Sie LVM mit NVMe/FC"] - Konfigurieren Sie Logical Volume Manager (LVM) mit NVMe über Fibre Channel für hochleistungsfähigen Blockspeicher unter Verwendung des modernen NVMe-Protokolls.
* link:proxmox-ontap-nvme-tcp.html["Konfigurieren Sie LVM mit NVMe/TCP"] - Konfigurieren Sie Logical Volume Manager (LVM) mit NVMe über TCP für hochleistungsfähigen Blockspeicher über Standard-Ethernet-Netzwerke unter Verwendung des modernen NVMe-Protokolls.

