---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Ein FC-basierter VMFS-Datenspeicher auf ONTAP dient als Hauptspeicher für eine VCF Workload-Domäne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Anwendungsfall wird die Vorgehensweise zum Einrichten eines Fibre Channel (FC) VMFS Datenspeichers auf ONTAP als primäre Speicherlösung für eine VMware Cloud Foundation (VCF) Workload-Domäne dargestellt. Diese Vorgehensweise fasst die erforderlichen Komponenten, Konfigurationsschritte und den Bereitstellungsprozess zusammen.



[[benefits-of-fibre-channel]]
== Vorteile von Fibre Channel

*Hohe Leistung:* FC bietet Hochgeschwindigkeitsdatenübertragungsraten und ist daher ideal für Anwendungen, die einen schnellen und zuverlässigen Zugriff auf große Datenmengen erfordern.

*Geringe Latenz:* Sehr geringe Latenz, die für leistungssensible Anwendungen wie Datenbanken und virtualisierte Umgebungen entscheidend ist.

*Zuverlässigkeit:* FC-Netzwerke sind für ihre Robustheit und Zuverlässigkeit bekannt und verfügen über Funktionen wie integrierte Redundanz und Fehlerkorrektur.

*Dedizierte Bandbreite:* FC bietet dedizierte Bandbreite für Speicherverkehr und reduziert so das Risiko einer Netzwerküberlastung.

Weitere Informationen zur Verwendung von Fibre Channel mit NetApp -Speichersystemen finden Sie unter https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["SAN-Bereitstellung mit FC"] .



[[scenario-overview]]
== Szenarioübersicht

Dieses Szenario umfasst die folgenden allgemeinen Schritte:

* Erstellen Sie eine Storage Virtual Machine (SVM) mit logischen Schnittstellen (LIFs) für FC-Verkehr.
* Sammeln Sie WWPN-Informationen der bereitzustellenden Hosts und erstellen Sie entsprechende Initiatorgruppen auf dem ONTAP Speichersystem.
* Erstellen Sie ein FC-Volume auf dem ONTAP -Speichersystem.
* Initiatorgruppen dem erstellten FC-Volume zugeordnet.
* Nutzen Sie Single-Initiator-Target-Zoning auf FC-Switches.  Erstellen Sie für jeden Initiator eine Zone (Einzelinitiatorzone).
+
** Fügen Sie für jede Zone ein Ziel ein, das die logische ONTAP FC-Schnittstelle (WWPN) für die SVMs ist.  Es sollten mindestens zwei logische Schnittstellen pro Knoten und SVM vorhanden sein.  Verwenden Sie nicht die WWPN der physischen Ports.


* Einen Netzwerkpool für vMotion-Datenverkehr in vCenter erstellen.
* Hosts in vCenter für die Nutzung in einer Workload-Domäne bereitstellen.
* Eine Workload Domain in VCF Ops unter Verwendung eines VMFS auf FC-Datenspeichers als primärem Speicher bereitstellen.



NOTE: Diese Lösung ist für ONTAP Plattformen anwendbar, die FC-Speicher unterstützen, einschließlich NetApp ASAr2, AFF und FAS.



[[prerequisites]]
== Voraussetzungen

In diesem Szenario werden die folgenden Komponenten und Konfigurationen verwendet:

* Ein ONTAP AFF, ASA oder FAS Storage-System mit FC-Ports, die an FC-Switches angeschlossen sind.
* SVM mit FC-Lifs erstellt.
* vSphere mit FC-HBAs, die mit FC-Switches verbunden sind.
* Auf FC-Switches ist eine einzelne Initiator-Ziel-Zonierung konfiguriert.
* Es ist sicherzustellen, dass die SVM Multipathing-Richtlinie auf Aktiv/Aktiv gesetzt ist.



NOTE: NetApp empfiehlt Multipath für FC-LUNs.



[[deployment-steps]]
== Bereitstellungsschritte



[[vcf-workload-domain-default-cluster]]
=== VCF Workload Domain - Standardcluster

Nachdem die Managementdomäne eingerichtet und betriebsbereit ist, kann die VCF Workload-Domäne erstellt werden:

* Verwendung der VCF Ops UI. Die vSphere Hosts werden in vCenter in Betrieb genommen und der Netzwerkpool wird konfiguriert. Mit System Manager oder der ONTAP API kann ein LUN auf vSphere Hosts bereitgestellt werden.
* Eine bestehende vSphere-Umgebung als neue Workload-Domäne importieren. ONTAP tools for VMware vSphere, System Manager oder ONTAP API können zur Bereitstellung des VMFS-Datenspeichers im vSphere-Cluster verwendet werden.




[[vcf-workload-domain-additional-cluster]]
=== VCF Workload Domain – zusätzlicher Cluster

Zur Erweiterung der Workload-Domäne mit einem zusätzlichen Cluster siehe  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Einem VCF-Domain kann ein SDDC Cluster hinzugefügt werden."].

Auf hoher Ebene sind die Schritte zum Hinzufügen eines zusätzlichen Clusters zur Workload-Domäne wie folgt: * Sicherstellen, dass die Hosts in Betrieb genommen und die Netzwerkpools in vCenter konfiguriert sind. * Die LUN wird auf dem ONTAP Storage-System bereitgestellt und den Hosts im zusätzlichen Cluster zugewiesen. * Neue SDDC-Cluster-Erstellung in der Workload-Domäne auf vCenter und dem Assistenten folgen, um den zusätzlichen Cluster zur Workload-Domäne hinzuzufügen.



[[additional-information]]
== Weitere Informationen

Informationen zur Konfiguration von ONTAP Speichersystemen finden Sie imlink:https://docs.netapp.com/us-en/ontap["ONTAP 9 Dokumentation"] Center.

Informationen zur Konfiguration von VCF sind unter link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation-Dokumentation"] zu finden.
