---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: Überprüfen Sie die Anforderungen für die Konvertierung eines vSphere 8-Clusters mit NetApp ONTAP NFS-Datenspeichern in eine VMware Cloud Foundation-Verwaltungsdomäne. 
---
= Bereitstellungsanforderungen für die Konvertierung von vCenter-Serverinstanzen in VCF-Verwaltungsdomänen mithilfe von NFS-Datenspeichern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie die Anforderungen für die Konvertierung eines vSphere 8-Clusters mit NetApp ONTAP NFS-Datenspeichern in eine VMware Cloud Foundation-Verwaltungsdomäne.

Der Konvertierungsprozess erfordert ein AFF oder ASA Speichersystem, SVMs und LIFs für FC-Verkehr, NFS-Zoning auf Switches, einen vSphere-Cluster mit ESXi-Hosts und vCenter sowie dedizierte Netzwerksegmente für vMotion.



== Infrastrukturanforderungen

Stellen Sie sicher, dass die folgenden Komponenten und Konfigurationen vorhanden sind.

* NetApp AFF -Speichersystem mit einer Storage Virtual Machine (SVM), die für die Zulassung von NFS-Verkehr konfiguriert ist.
* Im IP-Netzwerk erstellte logische Schnittstelle (LIF) zur Übertragung von NFS-Verkehr und mit der SVM verknüpft.
* Ein vSphere-Cluster mit 4 x ESXi-Hosts und einer vCenter-Appliance, die sich gemeinsam auf dem Cluster befindet.
* Verteilte Portgruppe, die für vMotion- und NFS-Speicherverkehr auf den zu diesem Zweck eingerichteten VLANs oder Netzwerksegmenten konfiguriert ist.
* Software zur VCF-Konvertierung. Die erforderliche Software finden Sie im https://support.broadcom.com/["Broadcom Support-Portal"] .
* Voraussetzungen für ONTAP -Tools.
+
Ausführliche Informationen zu den Voraussetzungen für ONTAP -Tools finden Sie unter https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["Voraussetzungen für ONTAP tools for VMware vSphere"] .

+
ONTAP tools for VMware vSphere können entweder in HA- oder Nicht-HA-Konfigurationen installiert werden.





== Zusätzliche Ressourcen

* Informationen zum unterstützten Speicher und andere Überlegungen zum Konvertieren oder Importieren von vSphere in VCF 5.2 finden Sie unter https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/considerations-before-converting-or-importing-existing-vsphere-environments-into-vcf-admin.html["Überlegungen vor dem Konvertieren oder Importieren vorhandener vSphere-Umgebungen in VMware Cloud Foundation"] .
* Informationen zum Konfigurieren von ONTAP Speichersystemen finden Sie imlink:https://docs.netapp.com/us-en/ontap["ONTAP 9 Dokumentation"] .
* Informationen zur Konfiguration von VCF finden Sie imlink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Dokumentation zu VMware Cloud Foundation 5.2"] .




== Wie geht es weiter?

Nachdem Sie die Bereitstellungsanforderungen überprüft haben,link:vmw-vcf-mgmt-nfs-deploy.html["Stellen Sie ONTAP -Tools bereit und stellen Sie den NFS-Datenspeicher bereit"] .
