---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-snapcenter.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= Erfahren Sie mehr über die Sicherung und Wiederherstellung virtueller Maschinen mit dem SnapCenter -Plug-in für VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Das SnapCenter Plug-in for VMware vSphere ermöglicht schnelle, VM-konsistente Sicherungs- und Wiederherstellungsvorgänge für VMs, Datenspeicher und VMDK-Dateien.  Dieses VMware-Plug-in lässt sich in SnapCenter Server integrieren, um anwendungsbasierte Sicherung und Wiederherstellung für anwendungsspezifische Plug-ins von SnapCenter zu unterstützen.



== Dokumentationsressourcen

Ausführliche Informationen finden Sie in den folgenden Dokumentationsressourcen.

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["SnapCenter Plug-in for VMware vSphere Dokumentation"]




== Lösungsressourcen

Beachten Sie die folgende 3-2-1-Backup-Lösung mit SnapCenter Plug-in for VMware vSphere und BlueXP backup and recovery für VMs.

Technischer Bericht:link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-321-dp-scv.html["3-2-1-Datenschutz für VMware mit SnapCenter -Plug-in und BlueXP backup and recovery für VMs"^]

Tech ONTAP Blog:link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["3-2-1-Datenschutz für VMware mit SnapCenter -Plug-in und BlueXP backup and recovery für VMs"]



== Videoressourcen

.SnapCenter Plug-in for VMware vSphere – Lösungsvoraussetzungen
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.SnapCenter Plug-in for VMware vSphere – Bereitstellung
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.SnapCenter Plug-in for VMware vSphere – Sicherungsworkflow
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.SnapCenter Plug-in for VMware vSphere – Wiederherstellungs-Workflow
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter – SQL-Wiederherstellungs-Workflow
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]