---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-migration.html 
keywords: vmware, getting, started, overview, netapp 
summary:  
---
= Erfahren Sie mehr über VMs von VMware vSphere bis hin zu ONTAP -Datenspeichern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vSphere-Administratoren können ihre Infrastruktur verbessern, indem sie Workloads auf NetApp ONTAP -Datenspeicher migrieren.  ONTAP bietet VM-fähige Snapshots, speichereffiziente Klone und nahtlose vMotion-Vorgänge und unterstützt gleichzeitig Storage Policy-Based Management (SPBM).  Ganz gleich, ob Sie von vSAN oder Legacy-Speicher migrieren oder Hybrid-Cloud-Bereitstellungen implementieren: ONTAP bietet verbesserte Leistung und vereinfachte Speichervorgänge für VMware-Umgebungen.

Diese Migration ermöglicht eine nahtlose Integration, verbesserten Datenschutz und größere Flexibilität bei der Verwaltung virtualisierter Umgebungen und gewährleistet einen reibungslosen Übergang mit minimalen Ausfallzeiten.



== Anwendungsfälle

Wenn Sie eine Migration auf ONTAP gestützte Datenspeicher in Erwägung ziehen, stehen Ihnen hinsichtlich Quelle und Ziel zahlreiche Migrationsoptionen zur Verfügung.

* Migration von Speichersystemen von Drittanbietern (einschließlich vSAN) zu ONTAP -Datenspeichern.
* Migration von VMs im selben vSphere-Cluster
* Migration von VMs über mehrere vSphere-Cluster
* Migration von VMs über vCenter-Server in derselben SSO-Domäne
* Migration von VMs über vCenter-Server in verschiedenen SSO-Domänen
* Migration von VMs zwischen Rechenzentrumsstandorten
* Migration von Speichersystemen von Drittanbietern (einschließlich vSAN) zu ONTAP -Datenspeichern.
* Migration von VMs in einer Hybrid-Cloud-Umgebung


Weitere Informationen zur Migration von VMware-Workloads zu ONTAP gestützten Datenspeichern finden Sie imlink:migrate-vms-to-ontap-datastore.html["Migrieren Sie VMs zu ONTAP -Datenspeichern"] .
