---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-vmsc.html 
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster 
summary:  
---
= Erfahren Sie mehr über die Integration der hohen Verfügbarkeit von ONTAP mit VMware vSphere Metro Storage Cluster (vMSC).
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Informationen zu den NetApp Lösungen, mit denen sich NetApp ONTAP Hochverfügbarkeit in VMware vSphere Metro Storage Cluster (vMSC) integrieren lässt. Dies stellt robuste Lösungen für die Management- und Workload-Domänen von VMware Cloud Foundation (VCF) bereit.

Diese Kombination gewährleistet kontinuierliche Datenverfügbarkeit, nahtloses Failover und Disaster Recovery an geografisch verteilten Standorten, wodurch die Ausfallsicherheit und Betriebskontinuität für kritische Workloads verbessert werden. SnapMirror active sync (SAN und NAS) ermöglicht den Weiterbetrieb von Geschäftsdiensten selbst bei einem vollständigen Standortausfall und unterstützt Anwendungen dabei, mithilfe einer sekundären Kopie transparent ein Failover durchzuführen. Es sind weder manuelle Eingriffe noch benutzerdefinierte Skripte erforderlich, um ein Failover mit SnapMirror active sync (SAN und NAS) auszulösen. Ein ONTAP Mediator wird verwendet, um den Zustand des primären Standorts zu überwachen und im Katastrophenfall automatisch auf den sekundären Standort umzuschalten. Der ONTAP Mediator wird auf einem separaten Server oder einer virtuellen Maschine bereitgestellt, die zu keinem der beiden Standorte gehört, wodurch das Quorum verfügbar bleibt und ein Split-Brain-Szenario vermieden wird.

Weitere Einzelheiten finden Sie in den folgenden Lösungen.

* link:vmw-vcf-vmsc-mgmt-smas.html["Stretch Cluster für Management Domain mit SnapMirror active sync (SAN und NAS)"]
* link:vmw-vcf-vmsc-mgmt-mcc.html["Stretch-Cluster für die Verwaltungsdomäne mit MetroCluster"]
* link:vmw-vcf-vmsc-viwld-smas.html["Stretch Cluster für Workload Domain mit SnapMirror active sync (SAN und NAS)"]
* link:vmw-vcf-vmsc-viwld-mcc.html["Stretch Cluster für Workload-Domäne mit MetroCluster"]

