---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-mgmt-supp-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS auf FC als zusätzlicher Speicher für VCF Workload- und Management-Domänen mit ONTAP tools for VMware
:allow-uri-read: 




[[vmfs-on-fc-as-supplemental-storage-for-vcf-workload-and-management-domains-using-ontap-tools-for-vmware]]
== VMFS auf FC als zusätzlicher Speicher für VCF Workload- und Management-Domänen mit ONTAP tools for VMware

[role="lead"]
In diesem Szenario zeigen wir, wie man einen VMFS-Datenspeicher mit Fiber Channel(FC)-Backend für Verwaltungs- und Workloaddomänen unter Verwendung von ONTAP -Tools bereitstellt.



[[benefits-of-fibre-channel]]
=== Vorteile von Fibre Channel

*Hohe Leistung:* FC bietet Hochgeschwindigkeitsdatenübertragungsraten und ist daher ideal für Anwendungen, die einen schnellen und zuverlässigen Zugriff auf große Datenmengen erfordern.

*Geringe Latenz:* Sehr geringe Latenz, die für leistungssensible Anwendungen wie Datenbanken und virtualisierte Umgebungen entscheidend ist.

*Zuverlässigkeit:* FC-Netzwerke sind für ihre Robustheit und Zuverlässigkeit bekannt und verfügen über Funktionen wie integrierte Redundanz und Fehlerkorrektur.

*Dedizierte Bandbreite:* FC bietet dedizierte Bandbreite für Speicherverkehr und reduziert so das Risiko einer Netzwerküberlastung.

Weitere Informationen zur Verwendung von Fibre Channel mit NetApp -Speichersystemen finden Sie unter https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["SAN-Bereitstellung mit FC"] .



[[scenario-overview]]
=== Szenarioübersicht

Der VCF Supplemental Datastore wird im Rahmen von Day-2-Operations mit vCenter bereitgestellt. Dieses Szenario umfasst die folgenden Schritte auf hoher Ebene:

* Bereitstellung von ONTAP -Tools in der Verwaltungsdomäne
* Workload-vCenter-Server bei ONTAP tools registrieren
* Definieren Sie das Storage-Backend im ONTAP -Tools-Plugin für VMware vSphere
* Bereitstellen von VMFS auf FC-Transport




[[prerequisites]]
=== Voraussetzungen

Dieses Szenario erfordert die folgenden Komponenten und Konfigurationen:

* Ein ONTAP Speichersystem mit FC-Ports, die mit FC-Switches verbunden sind.
* SVM mit FC-Lifs erstellt.
* vSphere mit FC-HBAs, die mit FC-Switches verbunden sind.
* Auf FC-Switches ist eine einzelne Initiator-Ziel-Zonierung konfiguriert.
+

NOTE: Verwenden Sie in der Zonenkonfiguration die logische SVM FC-Schnittstelle anstelle physischer FC-Ports auf ONTAP -Systemen.



NetApp empfiehlt Multipath für FC-LUNs.

Ausführliche Informationen zur Konfiguration von Fibre Channel auf ONTAP Speichersystemen finden Sie unter https://docs.netapp.com/us-en/ontap/san-management/index.html["SAN-Speicherverwaltung"] in der ONTAP 9-Dokumentation.

Weitere Informationen zur Verwendung von VMFS mit ONTAP Speichersystemen finden Sie imlink:vmw-vmfs-deploy.html["Bereitstellungshandbuch für VMFS"] .



[[deployment-steps-for-management-domain]]
=== Bereitstellungsschritte für die Verwaltungsdomäne

Führen Sie die folgenden Schritte aus, um ONTAP Tools bereitzustellen und damit einen VMFS-Datenspeicher in der VCF-Verwaltungsdomäne zu erstellen:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Stellen Sie ONTAP -Tools in der Verwaltungsdomäne bereit"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Definieren Sie das Speicher-Backend mithilfe der vSphere-Clientschnittstelle"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["Bereitstellen von VMFS auf FC"]




[[deployment-steps-for-workload-domain]]
=== Bereitstellungsschritte für die Workload Domain

Zur Bereitstellung von ONTAP tools und zur Erstellung eines VMFS-Datenspeichers in der VCF Workload-Domäne sind die folgenden Schritte erforderlich:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Arbeitslast vCenter registrieren, um das vCenter Plugin zu aktivieren"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Definieren Sie das Speicher-Backend mithilfe der vSphere-Clientschnittstelle"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["Bereitstellen von VMFS auf FC"]




[[additional-information]]
=== Weitere Informationen

Informationen zur Konfiguration von ONTAP Speichersystemen finden Sie imlink:https://docs.netapp.com/us-en/ontap["ONTAP 9 Dokumentation"] Center.

Informationen zur Konfiguration von VCF finden Sie unterlink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation-Dokumentation"] .



[[video-demo-for-this-solution]]
== Videodemo für diese Lösung

.Zusätzlicher Datenspeicher mit FC
video::96311abf-aa45-4ce9-984b-b4b001005bab[panopto,width=360]