---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: Die Anforderungen für die Konvergenz eines vSphere Clusters mit NetApp ONTAP NFS Datastores zu einer VMware Cloud Foundation Management-Domäne werden dargestellt. 
---
= Bereitstellungsanforderungen für die Konvergenz einer vCenter Serverinstanz mit der VCF-Management-Domäne unter Verwendung von NFS-Datenspeichern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Anforderungen für die Konvergenz eines vSphere Clusters mit NetApp ONTAP NFS Datastores zu einer VMware Cloud Foundation Management-Domäne werden dargestellt.

Für den Konvergenzprozess werden ein AFF- oder AFX-Speichersystem, SVMs und LIFs für NFS-Datenverkehr, NFS-VLANs auf Switches, ein vSphere Cluster mit vSphere Hosts und vCenter sowie ein dediziertes Netzwerksegment für vMotion benötigt.



[[infrastructure-requirements]]
== Infrastrukturanforderungen

Stellen Sie sicher, dass die folgenden Komponenten und Konfigurationen vorhanden sind.

* NetApp AFF oder AFX Speichersystem mit einer Storage Virtual Machine (SVM), die für NFS-Datenverkehr konfiguriert ist.
* Im IP-Netzwerk erstellte logische Schnittstelle (LIF) zur Übertragung von NFS-Verkehr und mit der SVM verknüpft.
* Ein vSphere Cluster mit mindestens 2 vSphere Hosts und einer vCenter Appliance, die sich auf dem Cluster befindet.
* Verteilte Portgruppe, die für vMotion- und NFS-Speicherverkehr auf den zu diesem Zweck eingerichteten VLANs oder Netzwerksegmenten konfiguriert ist.
* VCF Installer Tool zur Konvergenz des vCenter mit der VCF Management-Domäne.
* Voraussetzungen für ONTAP -Tools.
+
Ausführliche Informationen zu den Voraussetzungen für ONTAP -Tools finden Sie unter https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["Voraussetzungen für ONTAP tools for VMware vSphere"] .

+
ONTAP tools for VMware vSphere können entweder in HA- oder Nicht-HA-Konfigurationen installiert werden.





[[additional-resources]]
== Zusätzliche Ressourcen

* Informationen zu unterstützten Speichersystemen und weiteren Aspekten der Konvergenz von vSphere zu VCF sind unter  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["Unterstützte und nicht unterstützte Konfigurationen für die Konvergenz zu VCF"] zu finden.
* Informationen zum Konfigurieren von ONTAP Speichersystemen finden Sie imlink:https://docs.netapp.com/us-en/ontap["ONTAP 9 Dokumentation"] .
* Informationen zur Konfiguration von VCF sind in der link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation 9.1 Dokumentation"]Dokumentation zu finden.




[[whats-next]]
== Wie geht es weiter?

Nachdem Sie die Bereitstellungsanforderungen überprüft haben,link:vmw-vcf-mgmt-nfs-deploy.html["Stellen Sie ONTAP -Tools bereit und stellen Sie den NFS-Datenspeicher bereit"] .
