---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs 
summary:  
---
= Verwenden Sie einen NFS-Datenspeicher auf ONTAP als Hauptspeicher für die VCF-Verwaltungsdomäne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Anwendungsfall wird die Vorgehensweise zum Erstellen eines NFS-Datenspeichers auf ONTAP als primärer Speicher für die VMware Cloud Foundation (VCF) Management-Domäne dargestellt. Diese Vorgehensweise fasst die erforderlichen Komponenten, Konfigurationsschritte und den Bereitstellungsprozess zusammen.



[[introduction]]
== Einführung

Wo angebracht, wird auf externe Dokumentationen für die durchzuführenden Schritte in vCenter verwiesen und auf diejenigen Schritte Bezug genommen, die speziell den Speicherkonfigurationsabschnitt betreffen.

Falls ein NFS 4.1 Datenspeicher für die primäre Datenspeicherung benötigt wird oder wenn eine bestehende NFS-basierte vSphere Umgebung mit ONTAP umgestellt wird, siehe link:vmw-vcf-mgmt-nfs.html["Konvergieren der vSphere Umgebung (NFS Datastore) zur VCF Management Domain"].


NOTE: Mit VCF Version 5.2 wurde die Möglichkeit eingeführt, eine bestehende vSphere 8 Umgebung in eine VCF Managementdomäne zu konvertieren oder als VCF VI Workloaddomänen zu importieren. Vor dieser Version war VMware vSAN die einzige Option für den primären Speicher der VCF Managementdomäne. NSX Controller VMs werden besser auf einem FC-basierten VMFS-Datenspeicher bereitgestellt oder mit einem dualen Netzwerk-Switch betrieben, um einen Single Point of Failure zu vermeiden. Wenn diese Optionen nicht verfügbar sind, kann vSAN für das Hosting dieser VMs verwendet werden.


NOTE: Diese Lösung ist für ONTAP Plattformen anwendbar, die NFS Speicher unterstützen, einschließlich NetApp AFF, AFX und FAS.



[[prerequisites]]
== Voraussetzungen

In diesem Szenario werden die folgenden Komponenten und Konfigurationen verwendet:

* NetApp -Speichersystem mit einer Storage Virtual Machine (SVM), die für die Zulassung von NFS-Verkehr konfiguriert ist.
* Im IP-Netzwerk wurde eine logische Schnittstelle (LIF) erstellt, die den NFS-Verkehr übertragen soll und mit der SVM verknüpft ist.
* Ein vSphere Cluster mit mindestens 2 vSphere Hosts.
* NFS-Datenspeicher, der auf einem der vSphere Hosts mit demselben NFS-Server und Exportpfad eingebunden ist, der für die Managementdomäne verwendet wird.



NOTE: Beim Bereitstellen einer VCF Domain überprüft VCF die Verbindung zum NFS Server. Dies erfolgt mithilfe des Management-Adapters auf den vSphere Hosts, bevor ein zusätzlicher vmkernel Adapter mit der NFS IP-Adresse hinzugefügt wird. Daher ist sicherzustellen, dass entweder 1) das Management-Netzwerk zum NFS Server routbar ist oder 2) dem SVM, der das NFS Datastore Volume hostet, eine LIF für das Management-Netzwerk hinzugefügt wurde, damit die Validierung erfolgen kann.

* Sicherstellen, dass das ONTAP NFS VAAI Tool auf einem der vSphere Hosts installiert ist, das als Vorlage für das Cluster-Image ausgewählt werden kann.
* VCF Installer Tool bereitstellen.


Informationen zur Konfiguration von ONTAP Speichersystemen finden Sie imlink:https://docs.netapp.com/us-en/ontap["ONTAP 9 Dokumentation"] Center.

Informationen zur Konfiguration von VCF sind unter link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation-Dokumentation"] zu finden.



[[deployment-steps]]
== Bereitstellungsschritte



[[management-domain-default-cluster]]
=== Verwaltungsdomäne – Standardcluster

Das VCF Installer tool unterstützt VMFS auf FC-, NFS v3- und vSAN-Datenspeichern für die Management-Domäne. Die folgenden Schritte zeigen das Verfahren zur Bereitstellung einer Management-Domäne mit einem NFS v3-basierten Datenspeicher auf ONTAP als Hauptspeicher.


NOTE: Der nConnect-Wert für den NFS-Datenspeicher sollte nach der Bereitstellung überprüft oder angepasst werden.

Weitere Informationen zur Nutzung einer bestehenden vSphere-Umgebung sind unter link:vmw-vcf-mgmt-nfs.html["Konvergieren der vSphere Umgebung (NFS Datastore) zur VCF Management Domain"] zu finden.



[[management-domain-additional-cluster]]
=== Verwaltungsdomäne – Zusätzlicher Cluster

Zur Erweiterung der Managementdomäne um einen zusätzlichen Cluster siehe  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Einem VCF-Domain kann ein SDDC Cluster hinzugefügt werden."].

Auf hoher Ebene sind die Schritte zum Hinzufügen eines zusätzlichen Clusters zur Managementdomäne wie folgt: * Es ist sicherzustellen, dass die Hosts in Betrieb genommen und die Netzwerkpools in vCenter konfiguriert sind. * Das NFS-Datenspeichervolume wird auf dem ONTAP Storage-System bereitgestellt und an die Hosts im zusätzlichen Cluster exportiert. * Die Erstellung eines neuen SDDC-Clusters in der Managementdomäne auf vCenter erfolgt und der Assistent wird genutzt, um den zusätzlichen Cluster zur Managementdomäne hinzuzufügen.



[[additional-information]]
== Weitere Informationen

Informationen zur Konfiguration von ONTAP Speichersystemen finden Sie imlink:https://docs.netapp.com/us-en/ontap["ONTAP 9 Dokumentation"] Center.

Informationen zur Konfiguration von VCF sind unter link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation-Dokumentation"] zu finden.
