---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-otv.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= Erfahren Sie mehr über die Verwaltung virtueller Maschinen mit ONTAP tools for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere optimiert das Lifecycle-Management für VMs unter Verwendung von NetApp Storage. Administratoren können Storage direkt über den vCenter Server managen, was den Betrieb vereinfacht und die Skalierbarkeit verbessert. Wichtige Komponenten wie das vSphere Client Plug-in, der VASA Provider und der Storage Replication Adapter (SRA) optimieren die Provisionierung, das Performance Monitoring und das Disaster Recovery.



[[introduction]]
== Einführung

Es ermöglicht Administratoren, den Speicher innerhalb des vCenter Servers direkt zu verwalten und die Speicher- und Datenverwaltung für VMware-Umgebungen zu vereinfachen.  Das Plug-In-Tool für den VMware vSphere-Client ist darauf ausgelegt, Plug-In-Funktionen in den vSphere-Client zu integrieren, ohne dass eine Ausführung innerhalb von vCenter Server erforderlich ist.  Dies bietet Plug-In-Isolierung und ermöglicht die Skalierung von Plug-Ins, die in großen vSphere-Umgebungen ausgeführt werden.



[[ontap-tools-components]]
== ONTAP Tools-Komponenten

* *vSphere Client-Plug-in* Das Plug-in umfasst die in den vSphere Client integrierte Schnittstelle, über die Sie Storage Controller hinzufügen, Datastores provisionieren, die Performance von Datastores überwachen sowie ESXi Host-Einstellungen anzeigen und aktualisieren können. In ONTAP tools 9.x wird diese Komponente als Virtual Storage Console (VSC) bezeichnet.
* *VASA-Anbieter* Die VMware vSphere APIs for Storage Awareness (VASA)-Anbieter für ONTAP senden Informationen über den von VMware vSphere verwendeten Speicher an den vCenter Server und ermöglichen so die Bereitstellung von VMware Virtual Volumes (vVols)-Datenspeichern, die Erstellung und Verwendung von Speicherkapazitätsprofilen, die Konformitätsprüfung und die Leistungsüberwachung.
* *Storage Replication Adapter (SRA)* Wenn SRA aktiviert ist und mit VMware Site Recovery Manager (SRM) verwendet wird, erleichtert es die Wiederherstellung von vCenter Server-Datenspeichern und virtuellen Maschinen im Falle eines Fehlers und ermöglicht die Konfiguration geschützter Sites und Wiederherstellungssites für die Notfallwiederherstellung.


Weitere Informationen finden sich in der Dokumentation zu ONTAP tools for VMware vSphere für Ihre Version:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["ONTAP tools for VMware vSphere 10.x Dokumentation"^] (neueste Version)
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["ONTAP tools for VMware vSphere 9.x Dokumentation"^]

