---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Verwenden Sie einen FC-basierten VMFS-Datenspeicher auf ONTAP als Hauptspeicher für die VCF-Verwaltungsdomäne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In diesem Anwendungsfall wird die Vorgehensweise zur Erstellung eines FC-basierten VMFS Datenspeichers auf ONTAP als primärer Speicher für die VMware Cloud Foundation (VCF) Management Domain dargestellt. Diese Vorgehensweise fasst die erforderlichen Komponenten, Konfigurationen und Bereitstellungsschritte zusammen.



[[introduction]]
== Einführung

Wo angebracht, wird auf externe Dokumentationen für die durchzuführenden Schritte in vCenter verwiesen und auf diejenigen Schritte Bezug genommen, die speziell den Speicherkonfigurationsabschnitt betreffen.

Informationen zur Konvertierung eines bestehenden VMFS-Datenspeichers (einschließlich iSCSI und NVMe-oF) in einer vSphere-Umgebung mit ONTAP finden sich unter link:vmw-vcf-mgmt-vmfs.html["Konvergieren vSphere Environment (VMFS-Datenspeicher) zur VCF Management Domain"].


NOTE: Mit VCF Version 5.2 wurde die Möglichkeit eingeführt, eine bestehende vSphere 8 Umgebung in eine VCF Managementdomäne zu konvertieren oder als VCF VI Workloaddomänen zu importieren. Vor dieser Version war VMware vSAN die einzige Option für den primären Speicher der VCF Managementdomäne. NSX Controller VMs werden besser auf einem FC-basierten VMFS-Datenspeicher bereitgestellt oder mit einem dualen Netzwerk-Switch betrieben, um einen Single Point of Failure zu vermeiden. Wenn diese Optionen nicht verfügbar sind, kann vSAN für das Hosting dieser VMs verwendet werden.


NOTE: Diese Lösung ist für ONTAP -Plattformen anwendbar, die FC-Speicher unterstützen, einschließlich NetApp ASA, AFF und FAS.



[[prerequisites]]
== Voraussetzungen

In diesem Szenario werden die folgenden Komponenten und Konfigurationen verwendet:

* NetApp -Speichersystem mit einer Storage Virtual Machine (SVM), die für die Zulassung von FC-Verkehr konfiguriert ist.
* Auf dem FC-Fabric wurden logische Schnittstellen (LIF) erstellt, die den FC-Verkehr übertragen sollen und mit der SVM verknüpft sind.
* Zoning wurde so konfiguriert, dass auf FC-Switches für Host-HBAs und Speicherziele ein einzelnes Initiator-Ziel-Zoning verwendet wird.
* Auf einem der vSphere Hosts im Cluster wird ein VMFS Datenspeicher (mit FC LUN) erstellt.


Informationen zur Konfiguration von ONTAP Speichersystemen finden Sie imlink:https://docs.netapp.com/us-en/ontap["ONTAP 9 Dokumentation"] Center.

Informationen zur Konfiguration von VCF sind unter link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation-Dokumentation"] zu finden.



[[deployment-steps]]
== Bereitstellungsschritte



[[management-domain-default-cluster]]
=== Verwaltungsdomäne – Standardcluster

Das VCF Installer tool unterstützt VMFS auf FC-, NFS v3- und vSAN-Datenspeichern für die Management-Domäne. Die folgenden Schritte beschreiben das Verfahren zur Bereitstellung einer Management-Domäne mit einem FC-basierten VMFS-Datenspeicher auf ONTAP als Hauptspeicher.

Weitere Informationen zur Nutzung einer bestehenden vSphere-Umgebung sind unter link:vmw-vcf-mgmt-vmfs.html["Konvergieren vSphere Environment (VMFS-Datenspeicher) zur VCF Management Domain"] zu finden.



[[management-domain-additional-cluster]]
=== Verwaltungsdomäne – Zusätzlicher Cluster

Zur Erweiterung der Managementdomäne um einen zusätzlichen Cluster siehe  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Einem VCF-Domain kann ein SDDC Cluster hinzugefügt werden."].

Auf hoher Ebene sind die Schritte zum Hinzufügen eines zusätzlichen Clusters zur Managementdomäne wie folgt: * Sicherstellen, dass die Hosts in Betrieb genommen und die Netzwerkpools in vCenter konfiguriert sind. * Die LUN wird auf dem ONTAP Storage-System bereitgestellt und den Hosts im zusätzlichen Cluster zugewiesen. * Neue SDDC-Cluster-Erstellung in der Managementdomäne auf vCenter und dem Assistenten folgen, um den zusätzlichen Cluster zur Managementdomäne hinzuzufügen.



[[reference-video]]
== Referenzvideo

.Primärer Datenspeicher mit FC
video::9c51101c-292b-41ef-8dd5-b4cf0131dd62[panopto,width=360]


[[additional-information]]
== Weitere Informationen

Informationen zur Konfiguration von ONTAP Speichersystemen finden Sie imlink:https://docs.netapp.com/us-en/ontap["ONTAP 9 Dokumentation"] Center.

Informationen zur Konfiguration von VCF sind unter link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation-Dokumentation"] zu finden.
