---
sidebar: sidebar 
permalink: vmware/vmw-dr-gs.html 
keywords: vmware, getting, started, overview, netapp, console, disaster, recovery 
summary:  
---
= Erfahren Sie mehr über die Notfallwiederherstellung virtueller Maschinen mit NetApp Disaster Recovery.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Disaster Recovery automatisiert die Replikation und Wiederherstellung von VMware-VMs unter Verwendung von ONTAP -Speicher. Es unterstützt die Wiederherstellung von einer lokalen Umgebung in der VMware Cloud on AWS mit Amazon FSx for NetApp ONTAP oder einer anderen lokalen VMware-Umgebung.



== Einführung

Ein erfolgreicher Plan und eine Kombination von Technologien gewährleisten den Schutz kritischer Daten, Anwendungen und VMs.  Die Herausforderung bei DR besteht darin, das angemessene Schutzniveau und die damit verbundenen Kosten zu bestimmen.

ONTAP Arrays bieten eine integrierte Replikation, um Volumendaten und damit die virtuellen Maschinen, die sich auf den entsprechenden Datenspeicher-LUNs befinden, von einem Standort zum anderen zu übertragen. NetApp Disaster Recovery integriert sich in vSphere und automatisiert den gesamten Workflow für ein nahtloses Failover und Failback im Katastrophenfall.

Weitere Informationen zur NetApp Disaster Recovery finden Sie unterlink:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-overview.html["Überblick über die NetApp Disaster Recovery"^] Die



== Überlegungen

Der zeitaufwändigste Teil eines DR-Failovers in einer VMware vSphere-Umgebung ist die Ausführung der Schritte, die zum Inventarisieren, Registrieren, Neukonfigurieren und Einschalten der VMs am DR-Standort erforderlich sind. Eine ideale Lösung hat sowohl einen niedrigen RPO (gemessen in Minuten) als auch einen niedrigen RTO (gemessen in Minuten bis Stunden). Ein Faktor, der bei einer DR-Lösung oft übersehen wird, ist die Möglichkeit, die DR-Lösung in regelmäßigen Abständen effizient zu testen.

Berücksichtigen Sie beim Entwerfen einer DR-Lösung die folgenden Faktoren:

* Das Wiederherstellungszeitziel (RTO). Die RTO gibt an, wie schnell sich ein Unternehmen von einem Desaster erholen kann, oder genauer gesagt, wie lange es dauert, den Wiederherstellungsprozess auszuführen, um die Geschäftsdienste wieder verfügbar zu machen.
* Das Wiederherstellungspunktziel (RPO). Das RPO gibt an, wie alt die wiederhergestellten Daten nach ihrer Bereitstellung im Verhältnis zum Zeitpunkt des Katastrophenfalls sind.
* Skalierbarkeit und Anpassungsfähigkeit. Zu diesem Faktor gehört die Möglichkeit, die Speicherressourcen bei steigender Nachfrage schrittweise zu erweitern.


Weitere technische Informationen zu den verfügbaren Lösungen finden Sie unter:

* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-nfs.html["DR mit NetApp Disaster Recovery für NFS-Datenspeicher"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-dr-vmfs.html["DR mit NetApp Disaster Recovery für VMFS-Datenspeicher"^]

