---
sidebar: sidebar 
permalink: videos/hybrid-cloud-videos.html 
summary: Videos und Demos zu Hybrid-Cloud-Virtualisierungslösungen mit NetApp 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= Sehen Sie sich Videos zur hybriden MultiCloud-Virtualisierung mit NetApp an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Entdecken Sie, wie NetApp die Hybrid-Cloud-Virtualisierung auf den wichtigsten Hybrid-Multi-Cloud-Plattformen ermöglicht.  Sehen Sie sich Videos an, die Red Hat OpenShift Service auf AWS (ROSA) mit FSx ONTAP und NetApp HCI Lösungen für virtualisierte Workloads demonstrieren.



== Red Hat OpenShift Service auf AWS (ROSA) mit FSx ONTAP

.Amazon FSx for NetApp ONTAP mit Red Hat OpenShift Service auf AWS unter Verwendung der gehosteten Steuerebene
video::213061d2-53e6-4762-a68f-b21401519023[panopto,width=360]
.Integration von FSx ONTAP mit Trident
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.Snapshot/Wiederherstellung für Anwendungen auf Red Hat OpenShift Service auf AWS (ROSA)-Clustern mit Amazon FSx ONTAP -Speicher
video::36ecf505-5d1d-4e99-a6f8-b11c00341793[panopto,width=360]
.Failover und Failback von Apps auf ROSA mit FSx ONTAP
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]


== NetApp HCI -Lösungen

.NetApp HCI für Red Hat OpenShift auf Red Hat Virtualization
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]