---
sidebar: sidebar 
permalink: opennebula/opennebula-ontap-fc.html 
keywords: netapp, opennebula, lvm thin, fc, fibre channel, lvm, ontap, storage 
summary: 'Konfigurieren Sie den Logical Volume Manager (LVM)-Datenspeicher mit Fibre Channel für OpenNebula unter Verwendung von ONTAP. Dieses Verfahren umfasst die Multipath-Konfiguration, die LUN-Bereitstellung, die Einrichtung der Initiatorgruppe und die Erstellung der Volume-Gruppe für den gemeinsam genutzten Datenspeicher.' 
---
= Konfigurieren Sie LVM Thin mit ONTAP FC für OpenNebula
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Konfigurieren Sie den Logical Volume Manager (LVM)-Datenspeicher für die gemeinsame Nutzung von Speicher über OpenNebula-Hosts mithilfe des Fibre Channel-Protokolls mit NetApp ONTAP. Diese Konfiguration ermöglicht Blockspeicherzugriff mit hoher Leistung und niedriger Latenz.



== Erste Aufgaben des Virtualisierungsadministrators

Erledigen Sie diese ersten Aufgaben, um OpenNebula-Hosts für die FC-Konnektivität vorzubereiten und die notwendigen Informationen für den Speicheradministrator zu sammeln.

. Prüfen Sie, ob zwei HBA-Schnittstellen verfügbar sind.
. Stellen Sie sicher, dass multipath-tools auf allen OpenNebula Hosts installiert ist und beim Systemstart automatisch startet.
+
[role="tabbed-block"]
====
.Debian/Ubuntu
--
[source, shell]
----
apt list | grep multipath-tools
# If need to install, execute the following line.
apt-get install multipath-tools
# If /etc/multipath.conf is not present, first make sure the multipathd service is started.
systemctl enable --now multipathd
----
--
.RHEL/AlmaLinux
--
[source, shell]
----
dnf list installed | grep device-mapper-multipath
# If need to install, execute the following line.
dnf install device-mapper-multipath
# If /etc/multipath.conf is not present, first make sure the multipathd service is started.
systemctl enable --now multipathd
----
--
====
. Sammeln Sie die WWPN aller OpenNebula Hosts und geben Sie diese an den Speicheradministrator und den Administrator weiter, der für die Fabric-Zonierung zuständig ist.
+
[source, shell]
----
cat /sys/class/fc_host/host*/port_name
----




== Aufgaben des Speicheradministrators

Wenn Sie ONTAP noch nicht kennen, nutzen Sie den System Manager für eine bessere Benutzererfahrung.

. Stellen Sie sicher, dass die SVM mit aktiviertem FC-Protokoll verfügbar ist. Folgen link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["ONTAP 9 Dokumentation"]Die
. Erstellen Sie zwei LIFs pro Controller, die für FC vorgesehen sind. Sammeln Sie die WWPN-Adressen der erstellten FC-LIFs und stellen Sie sie dem Administrator zur Verfügung, der für die Fabric-Zonierung zuständig ist.
. Erstellen Sie eine Initiatorgruppe und fügen Sie die Host-FC-Initiatoren hinzu. Typischerweise wird eine Initiatorgruppe für einen OpenNebula-Cluster erstellt. Schließen Sie Frontend-Server und Hypervisor-Hosts in dieselbe Initiatorgruppe ein, um sowohl Image- als auch System-Datenspeicher zu unterstützen.
. Erstellen Sie die LUN mit der gewünschten Größe auf der SVM und stellen Sie sie der im vorherigen Schritt erstellten igroup zur Verfügung. Stellen Sie sicher, dass der Anti-Ransomware-Schutz auf der Registerkarte „Sicherheit“ für ASA -Systeme und auf der Registerkarte „Volume-Sicherheit“ für AFF/ FAS -Systeme aktiviert ist.
. Benachrichtigen Sie den Virtualisierungsadministrator, dass die LUN erstellt wurde.




== Abschließende Aufgaben des Virtualisierungsadministrators

Führen Sie diese Aufgaben aus, um die FC LUN als gemeinsam genutzten LVM-Datenspeicher in OpenNebula zu konfigurieren.

. Stellen Sie eine SSH-Verbindung zu allen OpenNebula Servern her und führen Sie die folgenden Schritte auf jedem Host aus.
. Führen Sie  `rescan-scsi-bus.sh` oder  `echo "- - -" > /sys/class/scsi_host/host*/scan` aus, um den SCSI-Bus erneut zu scannen und neue LUNs zu erkennen.
. Überprüfen Sie, ob die LUN auf allen OpenNebula-Hosts mit  `lsblk -S` oder dem Befehl fdisk -l sichtbar ist. Notieren Sie sich den Gerätenamen (z. B. sde, sdf) für die erstellte LUN.
. Fügen Sie das Gerät zur Multipath-Konfiguration hinzu, indem Sie  `multipath -a /dev/<device_name>` ausführen. Führen Sie dann  `multipath -r` aus, um die Multipath-Konfiguration neu zu laden. Überprüfen Sie die Multipath-Konfiguration, indem Sie den Befehl  `multipath -ll` ausführen.
. Stellen Sie eine SSH-Verbindung zu einem der Frontend-Server her und erstellen Sie eine Konfigurationsdatei basierend auf dem gewünschten Datenspeichertyp. Eine vollständige Attributliste finden Sie  https://docs.opennebula.io/7.0/product/cluster_configuration/san_storage/lvm_drivers/["OpenNebula LVM-Dokumentation"]. Beispieldateien sind unten aufgeführt:
+
[role="tabbed-block"]
====
.Backup
--
.. Für Restic,


[listing]
----
$cat fc-restic.conf
NAME = "Backup-Restic-FC"
TYPE = "BACKUP_DS"

DS_MAD = "restic"
TM_MAD = "-"

RESTIC_PASSWORD = "<restic_password>"
RESTIC_SFTP_SERVER = "<backup server>"
----
.. Für Rsync,


[listing]
----
$cat fc-rsync.conf
NAME = "Backup-Rsync-FC"
TYPE = "BACKUP_DS"

DS_MAD = "rsync"
TM_MAD = "-"

RSYNC_USER = "<rsync_user>"
RSYNC_HOST = "<backup server>"
----
--
.Datei
[source, shell]
----
$cat fc-kernel.conf
NAME = "File-Kernel-FC"
TYPE = "FILE_DS"
DS_MAD = "fs"
TM_MAD = "local"
SAFE_DIRS = "/var/tmp/files"
----
.Bild
[source, shell]
----
$cat fc-image.conf
NAME = "Image-FC01"
TYPE = "IMAGE_DS"
DS_MAD = "fs"
TM_MAD = "fs_lvm_ssh"
DISK_TYPE = "block"
LVM_THIN_ENABLE = "yes"
----
.System
[source, shell]
----
$cat fc-system.conf
NAME = "System-FC02"
TYPE = "SYSTEM_DS"
TM_MAD = "fs_lvm_ssh"
DISK_TYPE = "block"
BRIDGE_LIST = "<space-separated list of OpenNebula hosts>" # If LUN not presented to frontend hosts
LVM_THIN_ENABLE = "yes"
----
====
. Führen Sie  `onedatastore create <configuration file>` aus. Notieren Sie sich die nach der Erstellung zurückgegebene Datenspeicher-ID.
+
[]
====
onedatastore create fc-system.conf ID: 107

====
. Erstellen Sie eine Volume-Gruppe auf der FC-LUN mit dem  `vgcreate <vg_name> <multipath_device>` Befehl. Für Image-Datenspeicher kann der Name der Volume-Gruppe beliebig gewählt werden. Für System-Datenspeicher muss der Name der Volume-Gruppe das Format  `vg-one-<datastore id>` haben. Dies ist erforderlich, damit OpenNebula die korrekte Volume-Gruppe für System-Datenspeicher identifizieren kann. Fahren Sie mit den folgenden Schritten fort, wenn Sie einen Backup-/Datei-/Image-Datenspeicher erstellen. Für System-Datenspeicher hier stoppen.
. Erstellen Sie einen logischen Volume-Thin-Pool mit dem  `lvcreate -l 100%FREE -n <logical volume name> <volume group name>` Befehl. Für Systemdatenspeicher erstellt OpenNebula den LVM-Thin-Pool bei Bedarf automatisch.
. Erstellen Sie ein Dateisystem auf dem logischen Volume mit dem  `mkfs.ext4 /dev/<volume group>/<logical volume>`-Befehl. Für Systemdatenspeicher ist keine Dateisystemerstellung erforderlich.
. Aktualisieren Sie /etc/fstab oder die Automount-Konfiguration, um den Datenspeicher mit den gewünschten Mount-Optionen einzubinden. Angenommen wird der Standardspeicherort /var/lib/one/datastores. Kann mit  `onedatastore show <datastore_id>` validiert werden. Falls nicht, prüfen Sie den Parameter DATASTORE_LOCATION in /etc/one/oned.conf. Stellen Sie sicher, dass der <datastore_id> Ordner unter dem Datenspeicherort existiert. Beispielhafte Einträge sind unten aufgeführt:
+
[role="tabbed-block"]
====
.Verwendung von /etc/fstab
--
[source, shell]
----
/dev/<vg name>/<logical volume> /var/lib/one/datastores/<datastore_id> ext4 _netdev,noauto,x-systemd.automount,nofail 0 2
----
--
.Automount verwenden
--
[source, shell]
----
/var/lib/one/datastores/<datastore_id> -fstype=ext4,_netdev,noauto,x-systemd.automount,nofail,rw :/dev/<vg name>/<logical volume>
----
--
====
. Mounten Sie den Datenspeicher mit  `mount -a` oder  `systemctl reload autofs`-Befehl.
. Überprüfen Sie mit dem Befehl mount, ob der Datenspeicher eingebunden ist, und überprüfen Sie die Datenspeicherkapazität mit dem  `onedatastore show <datastore_id>` Befehl.
. Stellen Sie sicher, dass der Benutzer und die Gruppe „oneadmin“ Eigentümer des Datenspeicherordners sind. Passen Sie die Berechtigungen mit dem  `chown -R oneadmin:oneadmin /var/lib/one/datastores/<datastore_id>` Befehl an.

